### ISSUE TITLE
Parameters not defined when using serverless-plugin-split-stacks

### ISSUE THREAD

**Issue by mwillbanks** [smoketurner/serverless-vpc-plugin#188]
When using the plugin: `serverless-plugin-split-stacks` many parameters cannot be referenced on the second function.  The first function in the serverless.yml will include the proper parameters, however, 2nd+ functions will not contain the proper resolutions.

It appears that this is happening due to the way they are exported.  As such, you will receive an error: "Template format error: Unresolved resource dependencies [AppSubnet1Parameter, AppSubnet3Parameter, AppSubnet4Parameter, AppSubnet2Parameter, LambdaExecutionSecurityGroupParameter] in the Resources block of the template." when defining out the remainder of the handlers.

The following is my custom configuration:
```
custom:
  splitStacks:
    perFunction: true
    perType: false
    perGroupFunction: false
  vpcConfig:
    cidrBlock: '10.10.0.0/16'
    createBastionHost: false
    createDbSubnet: true
    createFlowLogs: false
    createNatGateway: true
    createNatInstance: false
    createNetworkAcl: true
    zones:
      - us-west-2a
      - us-west-2b
      - us-west-2c
      - us-west-2d
    subnetGroups:
      - rds
    exportOutputs: true
```

The function definitions are rather simplistic:
```
functions:
  networkList:
    handler: handler.networkList
    events:
      - http:
          method: get
          path: network
          cors: true
  networkRead:
    handler: handler.networkRead
    events:
      - http:
          method: get
          path: network/{id}
          cors: true
          request:
            parameters:
              path:
                id: true
```

The outputted information from the split stack shows that the parameters section within the first function contains the proper parameter types, whereas the second function will attempt to refer to the parameters but not actually define them.
