### ISSUE TITLE
Egress Only Gateway

### ISSUE THREAD

**Issue by Nemo64** [smoketurner/serverless-vpc-plugin#203]
I'm fairly new to VPC's and haven't tried to configure this but I ask anyways.

Wouldn't [Egress-Only Internet Gateways](https://docs.aws.amazon.com/vpc/latest/userguide/egress-only-internet-gateway.html) be a viable alternative to nat gatways, provided all target networks use ipv6?

**Comment by jplock** [comment]
I haven't tried those and am not sure if Lambda will use those or not if present.  Happy to review a PR if you wanted to try it out.

**Comment by Nemo64** [comment]
I tried around a little but didn't get far because the endpoint I was trying to access actually didn't support IPv6 🤦‍♂ 

If someone needs I starting point then this may help:
```
    EgressOnlyInternetGateway:
      Type: AWS::EC2::EgressOnlyInternetGateway
      Properties:
        VpcId: !Ref VPC
    AppRoute1:
      Type: AWS::EC2::Route
      DependsOn: InternetGatewayAttachment
      Properties:
        DestinationCidrBlock: "::/0"
        RouteTableId: !Ref AppRouteTable1
        EgressOnlyInternetGatewayId: !Ref EgressOnlyInternetGateway
    AppRoute2:
      Type: AWS::EC2::Route
      DependsOn: InternetGatewayAttachment
      Properties:
        DestinationCidrBlock: "::/0"
        RouteTableId: !Ref AppRouteTable2
        EgressOnlyInternetGatewayId: !Ref EgressOnlyInternetGateway
    AppRoute3:
      Type: AWS::EC2::Route
      DependsOn: InternetGatewayAttachment
      Properties:
        DestinationCidrBlock: "::/0"
        RouteTableId: !Ref AppRouteTable3
        EgressOnlyInternetGatewayId: !Ref EgressOnlyInternetGateway
```
For some reason I couldn't enter the routes using cloudformation, but manually entering them into the app route tables did work.
