### ISSUE TITLE
Example with elastiCache and Lambda on API Gateway

### ISSUE THREAD

**Issue by ahallora** [smoketurner/serverless-vpc-plugin#252]
Using `serverless-vpc-plugin` I'm having trouble connecting it all. I have a Lambda-function triggered via API Gateway that I want to execute a call to elastiCache. It deploys just fine but my lambda-function just timeouts after performing a `redisClient.get` ... 😢  I think the problem lies in missing access credentials for my lambda to the VPC where the elastiCache resides. 

I have scavenged the darkest corners of the deep web in search for a solution for more than two full days, I have come up short... I need your help! 🤓

Here's my `serverless.yml` for the **network**:

```yaml
service: obb-network
plugins:
  - serverless-vpc-plugin
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-central-1
  profile:
    obb
custom:
  vpcConfig:
    cidrBlock: '10.0.0.0/16'
     createNatGateway: false
    createNetworkAcl: false
    createDbSubnet: true
    createFlowLogs: false
    createBastionHost: false 
    createNatInstance: false
    subnetGroups:
      - elasticache
    exportOutputs: true
```

And here's my `serverless.yml` for the **API Gateway** and **elastiCache**:
```yaml
service: obb-api
custom:
  networkStack: obb-network-${self:provider.stage} # this links the above network serverless
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-central-1
  profile:
    obb
  environment:
    redisHost:
      "Fn::GetAtt": [ElasticCacheCluster, RedisEndpoint.Address]
  iamRoleStatements: # perhaps this will provide passage to elastiCache 
    - Effect: Allow
      Action:
        - "elasticache:*"
      Resource: "*"

functions:
  hello:
    handler: hello.main
    events:
      - http:
          path: /
          method: get
          cors: true
          authorizer: aws_iam
    role: LambdaVPCAccessExecutionRole # perhaps this will provide passage to elastiCache 
    vpc: 
    securityGroupIds:
      - Fn::GetAtt: CacheSecurityGroup.GroupId
    subnetIds:
      - Fn::ImportValue: !Sub ${self:custom.networkStack}-ElastiCacheSubnetGroup

    # Role to append to lambda in order to connect to ElastiCache, I guess
    LambdaVPCAccessExecutionRole:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName: "${self:service}-${self:provider.stage}-${self:provider.region}-LambdaVPCAccessExecutionRole"
        AssumeRolePolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service: "lambda.amazonaws.com"
              Action: "sts:AssumeRole"
        Policies:
          - PolicyName: LambdaVPCAccessExecutionRolePolicy
            PolicyDocument:
              Statement:
                - Effect: Allow
                  Action:
                    - "elasticache:*"
                  Resource: "*"
        ManagedPolicyArns:
          - "arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"

    # Elasticache needs an inbound rule to open port 6379, I guess
    CacheSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Ingress for Redis Cluster
        VpcId:
          Fn::ImportValue: !Sub ${self:custom.networkStack}-VPC
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 6379
            ToPort: 6379
            SourceSecurityGroupId:
              Fn::ImportValue: !Sub ${self:custom.networkStack}-LambdaExecutionSecurityGroupId

    # Set up elasticache cluster, I guess
    ElasticCacheCluster:
      Type: AWS::ElastiCache::CacheCluster
      Properties:
        AutoMinorVersionUpgrade: true
        Engine: redis
        CacheNodeType: cache.t2.micro
        NumCacheNodes: 1
        CacheSubnetGroupName:
          Fn::ImportValue: !Sub ${self:custom.networkStack}-ElastiCacheSubnetGroup
        VpcSecurityGroupIds:
          - !Ref CacheSecurityGroup
```

**Comment by heygambo** [comment]
Hey, @ahallora did you figure it out by now?

I'm in your shoes atm.

**Comment by ahallora** [comment]
Sadly no. 😢  
My lambda just times out... Probably because I've messed up the VPC / IAM setup at some point. 

Here's a comment about what needs to be fixed, in order for lambda to connect to ElastiCache, but I couldn't get it working. Perhaps you have better luck (and persistance)? 🙏 

https://blog.theodo.com/2019/07/store-your-data-in-aws-serverless-architecture/#elasticache

**Comment by heygambo** [comment]
@ahallora I think I've figured it out!

I took your `networkStack` idea and made it work.
There was a problem with lambda timing out.
That's because of the Redis client holding the connection will prevent the event loop to be emptied.
AWS Lambda is waiting for that to happen.

While doing the first tests I thought it is timing out because lambda wasn't able to connect to Redis due to VPC or security rule issues.

Adding `context.callbackWaitsForEmptyEventLoop = false` to your lamdba function will make it end the request even though the event loop has not been emptied.

Reference:
https://dev.to/lambdastore/reuse-redis-connection-in-aws-lambda-5ena

**network** serverless.yml
```
service:
  name: app-network

plugins:
  - serverless-vpc-plugin

custom:
  vpcConfig:
    cidrBlock: '10.0.0.0/16'
    createNatGateway: false
    createNetworkAcl: false
    createDbSubnet: true
    createFlowLogs: true
    createNatInstance: false
    createParameters: true
    exportOutputs: true
    services:
      - kms
      - secretsmanager
    subnetGroups:
      - rds
      - redshift
      - elasticache
      - dax

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
```

**service** serverless.yml
```
service:
  name: app-service
plugins:
  - serverless-webpack
  - serverless-offline
  - offline-invalidate
custom:
  networkStack: app-network-${opt:stage, 'offline'}
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 512
  environment:
    REDIS_HOST:
      Fn::GetAtt:
        - Redis
        - RedisEndpoint.Address
  vpc:
    securityGroupIds:
      - Ref: LambdaSecurityGroup
    subnetIds:
      - Fn::ImportValue:
          Fn::Sub: ${self:custom.networkStack}-AppSubnet1
      - Fn::ImportValue:
          Fn::Sub: ${self:custom.networkStack}-AppSubnet2
      - Fn::ImportValue:
          Fn::Sub: ${self:custom.networkStack}-AppSubnet3

resources:
  Resources:
    LambdaSecurityGroup:
      Type: "AWS::EC2::SecurityGroup"
      Properties:
        GroupName: ${self:service}-${self:provider.stage}-lambda
        GroupDescription: Allows outgoing redis
        SecurityGroupEgress:
          - IpProtocol: -1
            FromPort: 6379
            ToPort: 6379
            CidrIp: 10.0.0.0/16
        VpcId:
          Fn::ImportValue:
            Fn::Sub: ${self:custom.networkStack}-VPC
    RedisSecurityGroup:
      Type: "AWS::EC2::SecurityGroup"
      Properties:
        GroupName: ${self:service}-${self:provider.stage}-redis
        GroupDescription: Allows ingoing redis
        SecurityGroupIngress:
          - IpProtocol: -1
            FromPort: 6379
            ToPort: 6379
            SourceSecurityGroupId:
              Ref: LambdaSecurityGroup
        VpcId:
          Fn::ImportValue:
            Fn::Sub: ${self:custom.networkStack}-VPC
    Redis:
      Type: 'AWS::ElastiCache::CacheCluster'
      Properties:
        AutoMinorVersionUpgrade: false
        AZMode: single-az
        CacheNodeType: cache.t3.micro
        Engine: redis
        EngineVersion: 5.0.6
        NumCacheNodes: 1
        CacheSubnetGroupName:
          Fn::ImportValue:
            Fn::Sub:
              ${self:custom.networkStack}-ElastiCacheSubnetGroup
        VpcSecurityGroupIds:
          - Ref: RedisSecurityGroup
```
