### ISSUE TITLE
Is it necessary to create a security group for RDS databases?

### ISSUE THREAD

**Issue by mnapoli** [smoketurner/serverless-vpc-plugin#270]
First of all, this plugin is amazing!

Now I just want to make sure I'm not overthinking this: if I deploy with this plugin, and I create a RDS instance inside the "db" subnet, then Lambda cannot access the database by default, correct?

The only way I managed to make it work was:

```yaml
plugins:
    - serverless-vpc-plugin

custom:
    vpcConfig:

resources:
    Resources:
        # RDS databases should be put inside this security group
        DBSecurityGroup:
            Type: 'AWS::EC2::SecurityGroup'
            Properties:
                GroupDescription: 'RDS database access from Lambda'
                VpcId: !Ref VPC
                SecurityGroupIngress:
                    -   Description: 'Allow inbound MySQL access from Lambda'
                        FromPort: 3306
                        IpProtocol: tcp
                        # Accept connections from the Lambda security group
                        SourceSecurityGroupId: !GetAtt LambdaExecutionSecurityGroup.GroupId
                        ToPort: 3306
```

i.e. I have to create a security group, and then use this one when creating the RDS instance.

Is that correct?

And if yes, would it make sense to have the plugin create this security group?
