### ISSUE TITLE
v1.0.0 gives this error: `TypeError: awsService[method] is not a function`

### ISSUE THREAD

**Issue by solsglasses** [smoketurner/serverless-vpc-plugin#299]
Your newest release v1.0.0 causes sls to fail with this error:

`TypeError: awsService[method] is not a function`

Using this very simple config:

```
service: vpc

provider:
  name: aws
  
plugins:
  - serverless-vpc-plugin

custom:
  vpcConfig:
    cidrBlock: '10.0.0.0/16'
    exportOutputs: true
```

There's a good chance I screwed something up after not fully comprehending the breaking changes that v1.0.0 brings. But if I screwed it up, chances are someone else will screw it up too. They'll google the error and his issue will guide them.
