### ISSUE TITLE
Hooking this up with EFS

### ISSUE THREAD

**Issue by jliebrand** [smoketurner/serverless-vpc-plugin#375]
Hi there - first of all, thanks for this plugin! It saves a lot of config time!

I was wondering if you could provide a little more examples on how to get the NAT to work. In short, I need to have a Lambda that can write to EFS *and* reach the internet. If I just create my own VPC for the EFS then the lambda can read/write to it, but I can't get out to the internet. I was hoping I could use this plugin to not have to manually set up all the NAT stuff, but I'm getting lost.

NAT, subnets, routes... none are my forte really, so hoping for a little help/example.

Placing the EFS on the AppSubnet, results in the lambda not being able to connect to it. Here's what I got so far:

```
resources:
  Resources:
    SharedFs:
      Type: AWS::EFS::FileSystem
      Properties:
        BackupPolicy:
          Status: ENABLED
        PerformanceMode: generalPurpose
        Encrypted: true
        LifecyclePolicies:
          - TransitionToIA: AFTER_30_DAYS

    MountTarget:
      Type: AWS::EFS::MountTarget
      Properties:
        FileSystemId: !Ref SharedFs
        SubnetId: !Ref AppSubnet1
        SecurityGroups:
          - !Ref AppSecurityGroup

    AccessPointResource:
      Type: AWS::EFS::AccessPoint
      Properties:
        FileSystemId: !Ref SharedFs
        PosixUser:
          Uid: 1001
          Gid: 1001
        RootDirectory:
          CreationInfo:
            OwnerGid: 1001
            OwnerUid: 1001
            Permissions: 770
          Path: /efs
```

But then I get:
The function couldn't connect to the Amazon EFS file system with access point.......... Check your network configuration and try again. (Service: AWSLambda; Status Code: 408; Error Code: EFSMountConnectivityException

Should it even be on the AppSubnet? Or use the public subnet?

**Comment by jplock** [comment]
I haven’t tried this yet but I would think it would work from the AppSubnet. To reach the Internet you do have to use either a NAT instance or a NAT Gateway (or don’t put the Lambda in a VPC). I’ll see if I can get another example going.

**Comment by jplock** [comment]
This might be an issue with the security group and it needing to open more ports to EFS.

**Comment by jliebrand** [comment]
Yeah so I use
```
  vpcConfig:
    createNatGateway: true
    exportOutputs: true
    zones:
      - us-east-1a
```

For the Nat Gateway - and then put EFS and the lambda in the AppSubnet with the AppSecurityGroup. But that didn't seem to work (as you say, maybe it needs some other ports?).

(ps. not putting the lamba in the vpc would mean it doesn't have access to the EFS, right?)
