### ISSUE TITLE
Using `createDbSubnet: false` and more than one entry in `zones` leads to a broken template

### ISSUE THREAD

**Issue by dirknilius** [smoketurner/serverless-vpc-plugin#382]
We created something like this:

```yaml
plugins:
  - serverless-vpc-plugin

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1

custom:
  vpcConfig:
    cidrBlock: "172.16.0.0/16"
    createNatGateway: 2
    createNetworkAcl: true
    createDbSubnet: false # <-- NOTE: we have db subnets disabled
    createFlowLogs: true
    zones:
      - eu-central-1a
      - eu-central-1b
```

This creates a broken template, as it has outputs for db subnets, but no actual subnet:

```json
"Outputs": {

    "RDSSubnetGroup": {
      "Description": "Subnet Group for rds",
      "Value": {
        "Ref": "RDSSubnetGroup"
      }
    },

```

The deployment fails with:

`Error: The CloudFormation template is invalid: Unresolved resource dependencies [RDSSubnetGroup] in the Outputs block of the template`

This works with only one AZ. Then no subnet group nor output will be created.
