### ISSUE TITLE
Issues connecting to RDS from Lambda using Application Security Group

### ISSUE THREAD

**Issue by cbarlow1993** [smoketurner/serverless-vpc-plugin#417]
I'm struggling to connect a lambda to an RDS instance deployed into the RDS DB group. The Lambda is deployed into the Application Subnet

Issue seems to be IP blocked and Lambdas cannot get access to the IP range of the RDS DB Subnet. The Lambda can correctly reach the internet.

Any advice or tips for troubleshooting would be appreciated.

```
service: test-vpc

plugins:
  - serverless-vpc-plugin

provider:
  name: aws
  stage: dev
  region: eu-central-1
custom:
  dotenv: 
    logging: true
  REGION: ${opt:region, self:provider.region}
  STAGE: ${opt:stage, self:provider.stage}
  vpcConfig:
    cidrBlock: '10.0.0.0/16'
 
    # if createNatGateway is a boolean "true", a NAT Gateway and EIP will be provisioned in each zone 
    # if createNatGateway is a number, that number of NAT Gateways will be provisioned 
    # createNatGateway: 1
 
    # When enabled, the DB subnet will only be accessible from the Application subnet 
    # Both the Public and Application subnets will be accessible from 0.0.0.0/0 
    createNetworkAcl: true
 
    # Whether to create the DB subnet 
    createDbSubnet: true
 
    # Whether to enable VPC flow logging to an S3 bucket 
    createFlowLogs: false

 
    # Whether to create a bastion host 
    createBastionHost: true
    bastionHostKeyName: REPLACED# required if creating a bastion host 
 
    # Whether to create a NAT instance 
    createNatInstance: true
 
    # Whether to create AWS Systems Manager (SSM) Parameters 
    createParameters: true
 
    # Optionally specify AZs (defaults to auto-discover all availabile AZs) 
    zones:
      - eu-central-1a
      - eu-central-1b
 
    # By default, S3 and DynamoDB endpoints will be available within the VPC 
    # see https://docs.aws.amazon.com/vpc/latest/userguide/vpc-endpoints.html 
    # for a list of available service endpoints to provision within the VPC 
    # (varies per region) 
    services:
      - kms
      - secretsmanager
 
    # Optionally specify subnet groups to create. If not provided, subnet groups 
    # for RDS, Redshift, ElasticCache and DAX will be provisioned. 
    subnetGroups:
      - rds
 
    # Whether to export stack outputs so it may be consumed by other stacks 
    exportOutputs: true
```
