### ISSUE TITLE
Unable to request outbound traffic with the default setting

### ISSUE THREAD

**Issue by siutsin** [smoketurner/serverless-vpc-plugin#44]
By default, without a `NAT Instance` or `NAT Gateway`, the subnets associated with the functions should route all traffic to the `Internet Gateway`. Hence the functions should have the ability to make outbound requests. However, all the outgoing traffics are blocked and timeout.

This issue can be resolved by provisioning a NAT instance/gateway in v0.6.0.

serverless.yml
```yml
service: serverless-vpc-plugin-example

frameworkVersion: '>=1.40.0 <2.0.0'

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-west-2
  memorySize: 128
  timeout: 6

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get

custom:
  vpcConfig:
    cidrBlock: '10.123.0.0/16'
#    createNatInstance: true

plugins:
  - serverless-vpc-plugin
  - serverless-webpack
```
handler.js
```js
'use strict'

const axios = require('axios')

module.exports.hello = async (event) => {
  const response = await axios.post('https://httpbin.org/post', { some: 'data' })
  return {
    statusCode: 200,
    body: JSON.stringify({
      message: 'Go Serverless v1.0! Your function executed successfully!',
      input: event,
      response: response.data
    })
  }
}
```

With NAT instance:
```json
{
  "message": "Go Serverless v1.0! Your function executed successfully!",
  "input": {
    ...
  },
  "response": {
    "args": {},
    "data": "{\"some\":\"data\"}",
    "files": {},
    "form": {},
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Content-Length": "15",
      "Content-Type": "application/json;charset=utf-8",
      "Host": "httpbin.org",
      "User-Agent": "axios/0.18.0"
    },
    "json": {
      "some": "data"
    },
    "origin": "...",
    "url": "https://httpbin.org/post"
  }
}
```

Without NAT instance:
```json
{
  "message": "Internal server error"
}
```

**Comment by siutsin** [comment]
So from the README, currently the setup of the subnets are:
- `AWS::EC2::Subnet` "Application" (/21) - default route is either `InternetGateway`, `NatGateway` or `NatInstance`
- `AWS::EC2::Subnet` "Public" (/22) - default route set `InternetGateway`
- `AWS::EC2::Subnet` "Database" (/22) - no default route set in routing table

What do you think if the subnets are defined as:
- `AWS::EC2::Subnet` "Public" (/22) - default route is either `InternetGateway`, `NatGateway` or `NatInstance`
- `AWS::EC2::Subnet` "Private" (/22) - default route is either `None`, `NatGateway` or `NatInstance`
- `AWS::EC2::Subnet` "Database" (/22) - no default route set in routing table

So the private subnet, it will only route `0.0.0.0/0` to `NatGateway` or `NatInstance` if they are provisioned.
Furthermore, a custom parameter to each functions to determine which subnet it should go. E.g.:

```yml
functions:
  hello:
    handler: handler.function1
    subnetType: public # default
  hello:
    handler: handler.function2
    subnetType: private
```
