### ISSUE TITLE
Problem with update from 0.10.0 to 1.0.1

### ISSUE THREAD

**Issue by korridor** [smoketurner/serverless-vpc-plugin#443]
I am using your plugin for a while now I think it is really a great plugin. (especially the example helped me a lot)

I tries to update to 1.0.1 from 0.10.0 and Cloudformation had a problem to delete the LambdaExecutionSecurityGroup. (error: resource sg-xxx has a dependent object) Cloudformation retried this for a while and then the deployment succeded.
The problem now is that the lambda cannot access the RDS instance. (I am using a RDS instance not a cluster)

```yaml
DBSecurityGroup:
  Type: 'AWS::EC2::SecurityGroup'
  Properties:
    GroupDescription: Access to Postgres
    VpcId:
      Ref: VPC
    SecurityGroupIngress:
      - SourceSecurityGroupId:
          Ref: BastionHostSecurityGroup
        Description: Bastion access to Postgres
        IpProtocol: tcp
        FromPort: 5432
        ToPort: 5432
      - SourceSecurityGroupId:
          Ref: LambdaExecutionSecurityGroup
        Description: Lambda access to Postgres
        IpProtocol: tcp
        FromPort: 5432
        ToPort: 5432
    Tags:
      - Key: Name
        Value:
          'Fn::Join':
            - '-'
            - - Ref: 'AWS::StackName'
              - rds
```

and I am using it in the DB instance like this:

```yaml
DBInstance:
  Type: 'AWS::RDS::DBInstance'
  Properties:
    AllocatedStorage: 20
    AllowMajorVersionUpgrade: true
    AutoMinorVersionUpgrade: true
    DBInstanceClass: db.t2.micro
    Port: 5432
    StorageType: gp2
    BackupRetentionPeriod: 7
    PreferredBackupWindow: '00:25-00:55'
    PreferredMaintenanceWindow: 'mon:03:37-mon:04:07'
    DBName: postgres
    Engine: postgres
    EngineVersion: '12.3'
    LicenseModel: postgresql-license
    DBSubnetGroupName:
      Ref: RDSSubnetGroup
    VPCSecurityGroups:
      - Ref: DBSecurityGroup
    AvailabilityZone:
      'Fn::Select':
        - 0
        - 'Fn::GetAZs': ''
    CopyTagsToSnapshot: true
    MasterUsername:
      'Fn::Join':
        - ''
        - - '{{resolve:secretsmanager:'
          - Ref: DBSecret
          - ':SecretString:username}}'
    MasterUserPassword:
      'Fn::Join':
        - ''
        - - '{{resolve:secretsmanager:'
          - Ref: DBSecret
          - ':SecretString:password}}'
    MultiAZ: false
    PubliclyAccessible: false
    Tags:
      - Key: Name
        Value:
          'Fn::Join':
            - '-'
            - - Ref: 'AWS::StackName'
              - rds
```

After the deployment I inspected the DBSecurityGroup in the AWS console and the two ingress security groups were successfully applied.
I rolled back for now, but I don't get why this is not working.

**Comment by jplock** [comment]
Is there an egress rule on the AppSecurityGroup allow port 5432 to the DBSecurityGroup?

**Comment by korridor** [comment]
I just checked and you are right the AppSecurityGroups does not allow access to the DBSecurityGroup.

<img width="1555" alt="image" src="https://user-images.githubusercontent.com/26689068/99187625-0508cc00-2758-11eb-882a-63c48dd23f45.png">

<img width="1550" alt="image" src="https://user-images.githubusercontent.com/26689068/99187636-19e55f80-2758-11eb-9c24-6e7dfd920a89.png">

Do you have any idea why this is happening.
My configuration looks like this:

```yaml
  vpcConfig:
    cidrBlock: '10.0.0.0/16'

    # if createNatGateway is a boolean "true", a NAT Gateway and EIP will be provisioned in each zone
    # if createNatGateway is a number, that number of NAT Gateways will be provisioned
    createNatGateway: 1

    # When enabled, the DB subnet will only be accessible from the Application subnet
    # Both the Public and Application subnets will be accessible from 0.0.0.0/0
    createNetworkAcl: false

    # Whether to create the DB subnet
    createDbSubnet: true

    # Whether to enable VPC flow logging to an S3 bucket
    createFlowLogs: false

    # Whether to create a bastion host
    createBastionHost: false
    bastionHostKeyName: ${self:custom.stageConfig.${self:provider.stage}.bastionHostKeyName}

    # Whether to create a NAT instance
    createNatInstance: false

    # Whether to create AWS Systems Manager (SSM) Parameters
    createParameters: true

    # Optionally specify AZs (defaults to auto-discover all available AZs)
    zones:
      - eu-central-1a
      - eu-central-1b
      - eu-central-1c

    # By default, S3 and DynamoDB endpoints will be available within the VPC
    # see https://docs.aws.amazon.com/vpc/latest/userguide/vpc-endpoints.html
    # for a list of available service endpoints to provision within the VPC
    # (varies per region)
    services:
      - kms
      - secretsmanager

    # Optionally specify subnet groups to create. If not provided, subnet groups
    # for RDS, Redshift, ElasticCache and DAX will be provisioned.
    subnetGroups:
      - rds

    # Whether to export stack outputs so it may be consumed by other stacks
    exportOutputs: true
```
