### ISSUE TITLE
Redshift, ElasticCache and Dax subnets are created even when not requested

### ISSUE THREAD

**Issue by PetroccoCo** [smoketurner/serverless-vpc-plugin#483]
Seems to be a near identical error to  #https://github.com/smoketurner/serverless-vpc-plugin/issues/382
Attempting to setup a super basic VPC just an elastic ip, public and app subnets. No db subnet nor Redshift, ElasticCache and Dax subnets getting an error message about RedshiftSubnetGroup.

`Error: The CloudFormation template is invalid: Unresolved resource dependencies [RedshiftSubnetGroup] in the Outputs block of the template`

``` yaml
vpcConfig:
    cidrBlock: '10.0.0.0/16'
    createNatGateway: 1
    createNetworkAcl: true
    createDbSubnet: false
    createParameters: true
    exportOutputs: true
```

The cloudformation-template-update-stack.json mentions all three subnet groups RedshiftSubnetGroup, ElastiCacheSubnetGroup, DAXSubnetGroup:
``` json
    "RedshiftSubnetGroup": {
      "Description": "Subnet Group for redshift",
      "Value": {
        "Ref": "RedshiftSubnetGroup"
      },
      "Export": {
        "Name": {
          "Fn::Sub": "${AWS::StackName}-RedshiftSubnetGroup"
        }
      }
    },
    "ElastiCacheSubnetGroup": {
      "Description": "Subnet Group for elasticache",
      "Value": {
        "Ref": "ElastiCacheSubnetGroup"
      },
      "Export": {
        "Name": {
          "Fn::Sub": "${AWS::StackName}-ElastiCacheSubnetGroup"
        }
      }
    },
    "DAXSubnetGroup": {
      "Description": "Subnet Group for dax",
      "Value": {
        "Ref": "DAXSubnetGroup"
      },
      "Export": {
        "Name": {
          "Fn::Sub": "${AWS::StackName}-DAXSubnetGroup"
        }
      }
    },
```

**Comment by jplock** [comment]
Are the subnet groups in the resources or just the outputs?

**Comment by blognat** [comment]
```
  vpcConfig:
    cidrBlock: '10.0.0.0/16'
    createDbSubnet: false
    createNatGateway: 1
    exportOutputs: true
```

seems familiar

`Error: The CloudFormation template is invalid: Unresolved resource dependencies [RedshiftSubnetGroup] in the Outputs block of the template`
