### ISSUE TITLE
Use subnets for parameters (${AppSubnet{1}})

### ISSUE THREAD

**Issue by patrickbussmann** [smoketurner/serverless-vpc-plugin#604]
```
provider:
    vpc:
        securityGroupIds:
            - ${AppSecurityGroup}
        subnetIds: ${AppSubnets~split}

custom:
    vpcConfig:
        cidrBlock: '10.0.0.0/16'
        createNatGateway: 1
        createDbSubnet: false
```

seems to be working.
But when I want to use it for my resources its broken.

```
resources:
    Resources:
        MountTargetA:
            Type: AWS::EFS::MountTarget
            Properties:
                SubnetId: ${AppSubnet{1}}
                SecurityGroups:
                    - ${AppSecurityGroup}
        MountTargetB:
            Type: AWS::EFS::MountTarget
            Properties:
                SubnetId: ${AppSubnet{2}}
                SecurityGroups:
                    - ${AppSecurityGroup}
        MountTargetC:
            Type: AWS::EFS::MountTarget
            Properties:
                SubnetId: ${AppSubnet{3}}
                SecurityGroups:
                    - ${AppSecurityGroup}
```

Error message:

```
An error occurred: EFSCacheMountTargetResourceA - 2 validation errors detected: Value '${AppSubnet{1}}' at 'subnetId' failed to satisfy constraint: Member must satisfy regular expression pattern: ^subnet-[0-9a-f]{8,40}$; Value '[${AppSecurityGroup}]' at 'securityGroups' failed to satisfy constraint: Member must satisfy constraint: [Member must have length less than or equal to 43, Member must have length greater than or equal to 11, Member must satisfy regular expression pattern: ^sg-[0-9a-f]{8,40}] (Service: AmazonElasticFileSystem; Status Code: 400; Error Code: ValidationException; Request ID: 569b3c04-42f3-47db-9cb8-1c630b090b28; Proxy: null).
```

Not working with `${self:provider.vpc.subnetIds.1}`, too.

**Comment by jplock** [comment]
I'm not actually sure the best way to address this since its confusing between what is a Serverless variable and what is a CloudFormation variable replacement.  You could use the CloudFormation `Fn::Select` function to get a specific index from a list of items, so this might work:

```yaml
resources:
    Resources:
        MountTargetA:
            Type: AWS::EFS::MountTarget
            Properties:
                SubnetId: !Select [0, ${AppSubnets~split}]
                SecurityGroups:
                    - ${AppSecurityGroup}
        MountTargetB:
            Type: AWS::EFS::MountTarget
            Properties:
                SubnetId:  !Select [1, ${AppSubnets~split}]
                SecurityGroups:
                    - ${AppSecurityGroup}
        MountTargetC:
            Type: AWS::EFS::MountTarget
            Properties:
                SubnetId:  !Select [2, ${AppSubnets~split}]
                SecurityGroups:
                    - ${AppSecurityGroup}
```

**Comment by patrickbussmann** [comment]
Ah yes thank you I got the solution. -> Using `!Ref`

```
resources:
    Resources:
        MountTargetA:
            Type: AWS::EFS::MountTarget
            Properties:
                FileSystemId: !Ref EFSCacheFileSystemResource
                SubnetId: !Ref AppSubnet1
                SecurityGroups:
                    - !Ref AppSecurityGroup
        MountTargetB:
            Type: AWS::EFS::MountTarget
            Properties:
                FileSystemId: !Ref EFSCacheFileSystemResource
                SubnetId: !Ref AppSubnet2
                SecurityGroups:
                    - !Ref AppSecurityGroup
        MountTargetC:
            Type: AWS::EFS::MountTarget
            Properties:
                FileSystemId: !Ref EFSCacheFileSystemResource
                SubnetId: !Ref AppSubnet3
                SecurityGroups:
                    - !Ref AppSecurityGroup
```

Interesting thing 😀
But working now.

Thanks.
