### ISSUE TITLE
Cannot export output undefined. Exported values must not be empty or whitespace-only.

### ISSUE THREAD

**Issue by mijndert** [smoketurner/serverless-vpc-plugin#704]
Getting this error while setting up a VPC using this plugin:

```yaml
service: commercetools

plugins:
  - serverless-vpc-plugin

provider:
  name: aws
  region: eu-central-1
  stage: stg
  vpc:
    securityGroupIds:
      -  # plugin will add LambdaExecutionSecurityGroup to this list
    subnetIds:
      -  # plugin will add the "Application" subnets to this list

custom:
  vpcConfig:
    enabled: true
    cidrBlock: '10.30.0.0/16'
    createNatGateway: 3
    createNetworkAcl: false
    createDbSubnet: false
    createFlowLogs: false
    createBastionHost: false
    createNatInstance: false
    createParameters: false
    services:
      - kms
      - secretsmanager
    exportOutputs: false
```
