### ISSUE TITLE
Security Groups are required to be in the same VPC

### ISSUE THREAD

**Issue by anilskalyane** [smoketurner/serverless-vpc-plugin#765]
Getting this error while setting up a VPC using this plugin:

```
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  stage: ${opt:stage, 'dev'}
  region: ${file(serverless.env.yml):${self:custom.stage}.REGION}
  vpc:
    securityGroupIds:
      - sg-xxxxxxxx
    subnetIds:
      - subnet-xxxxxx
      - subnet-xxxxxx
      - subnet-xxxxxx
```
Both subnet and security groups are there in the same VPC.
