### ISSUE TITLE
How to add rules to security group?

### ISSUE THREAD

**Issue by buddhaCode** [smoketurner/serverless-vpc-plugin#922]
Hi folks,
thanks for the great plugin. I am pretty new to the Serverless Framework. I need to add a rule to the created security group. Is there any way to reference the security group in the Resources section?

Best, Arne

**Comment by jawadst** [comment]
You can reference the CF outputs referenced on https://github.com/smoketurner/serverless-vpc-plugin#cloudformation-outputs

Example for adding an egress rule to the app security group:

```yaml
  AppEgressToDax:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      Description: 'Traffic to TLS DAX'
      IpProtocol: tcp
      FromPort: 9111
      ToPort: 9111
      GroupId: !GetAtt AppSecurityGroup.GroupId
      DestinationSecurityGroupId: 'group id'
```
